### ISSUE TITLE
inline styles and vendor prefix for values

### ISSUE THREAD

**Issue by GulberaTekin** [GulberaTekin/react#1970]
Original issue: https://github.com/facebook/react/issues/2020

How would I write the following css using inline styles?

``` css
.page-wrap {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
 }
```

Wouldn't be nice if react could internally automatically handle vendor prefixes (similar to stylus + nib)?
